#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/options_parser.y".
#

require 'racc/parser'


class OptionsParser < Racc::Parser

module_eval <<'..end lib/options_parser.y modeval..id8e02abf9c7', 'lib/options_parser.y', 86

def parse(str, allow_nested_groups = false)
  @str = str.strip

  @item_id = 0
  @allow_nested_groups = allow_nested_groups

  @parse_result = do_parse()
  make_nested_result(0, 0)[0]
end

def make_nested_result(pos, depth)
  result = []
  while true do
    entry = @parse_result[pos]
    if entry.nil? 
      return [result, pos]
    elsif entry[:group_depth]  # Is it a group?
      raise TypeError, "You can't currently nest groups for this type of form element" unless @allow_nested_groups || entry[:group_depth] <= 1
      if entry[:group_depth] <= depth # let the caller handle this
        return [result, pos]
      else
        res = make_nested_result(pos + 1, entry[:group_depth])
        result << res[0].unshift(entry[:name])
        pos = res[1]
      end
    else # item
      if entry[:item_depth] > depth + 1
        raise TypeError, "Item too deep for option groups: #{entry[:name]}"
      elsif entry[:item_depth] < depth + 1 # caller can handle this
        return [result, pos]
      else
        result << entry
        pos += 1
      end
    end
  end
end

def next_token
  if @str.size > 0
    case @str
    when /\A[\r\n]+/
      ret = [:NL, $&]
    when /\Aog\./
      ret = [:OPTGROUP, $&]
    when /\A[*]+/
      ret = [:DEFAULT_ITEM, $&]
    when /\A#+/
      ret = [:ITEM, $&]
    when /\A[^ \n\r:]+/
      ret = [:NAME, $&]
    when /\A:/
      ret = [:COLON, $&]
    when /\A[\t ]+/
      ret = [:SPACE, $&]
    else
      raise "Unrecognised symbol in string: #{@str.inspect}"
    end
    @str = $'
  else
    ret = [false, '$end']
  end
  return ret
end

def on_error(token_id, error_value, value_stack)
  raise TypeError.new("Unexpected '#{error_value}' before '#{@str}'")
end
..end lib/options_parser.y modeval..id8e02abf9c7

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 10, :_reduce_1,
 0, 10, :_reduce_2,
 2, 12, :_reduce_3,
 0, 12, :_reduce_none,
 1, 11, :_reduce_none,
 1, 11, :_reduce_none,
 4, 14, :_reduce_7,
 3, 16, :_reduce_8,
 0, 16, :_reduce_9,
 3, 17, :_reduce_10,
 3, 18, :_reduce_11,
 3, 18, :_reduce_12,
 3, 18, :_reduce_13,
 3, 18, :_reduce_14,
 0, 18, :_reduce_15,
 3, 19, :_reduce_16,
 3, 20, :_reduce_17,
 3, 20, :_reduce_18,
 3, 20, :_reduce_19,
 0, 20, :_reduce_20,
 4, 13, :_reduce_21,
 4, 13, :_reduce_22,
 2, 21, :_reduce_23,
 0, 21, :_reduce_24,
 1, 15, :_reduce_25,
 0, 15, :_reduce_26 ]

racc_reduce_n = 27

racc_shift_n = 55

racc_action_table = [
     3,    11,     3,     5,     6,     5,     6,    31,    23,    32,
    33,    36,    37,    38,    39,    31,    11,    32,    33,    36,
    37,    38,    39,    36,    37,    38,    39,    31,    26,    32,
    33,    36,    37,    38,    39,    31,    26,    32,    33,    36,
    37,    38,    39,    16,    21,    18,    23,    18,    11,    11,
    11,    11,    11,    11,    11,    16,    14,    11,    11,    11,
     9,    11 ]

racc_action_check = [
     0,    16,     9,     0,     0,     9,     9,    42,    17,    42,
    42,    44,    44,    44,    44,    43,    18,    43,    43,    45,
    45,    45,    45,    46,    46,    46,    46,    41,    19,    41,
    41,    30,    30,    30,    30,    25,    20,    25,    25,    47,
    47,    47,    47,    22,    14,    13,    26,    12,    31,    32,
    33,    36,    37,    38,    39,    10,     7,     6,     5,     3,
     1,    23 ]

racc_action_pointer = [
    -3,    58,   nil,    51,   nil,    50,    49,    56,   nil,    -1,
    52,   nil,    43,    41,    44,   nil,    -7,     4,     8,    23,
    31,   nil,    40,    53,   nil,    31,    42,   nil,   nil,   nil,
    27,    40,    41,    42,   nil,   nil,    43,    44,    45,    46,
   nil,    23,     3,    11,     7,    15,    19,    35,   nil,   nil,
   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -2,    -4,    -5,   -26,    -6,   -26,   -26,   -27,    -1,    -2,
    -9,   -25,   -27,   -27,   -27,    -3,   -26,   -27,   -26,   -24,
   -24,    55,    -9,   -26,    -7,   -20,   -27,   -21,   -22,    -8,
   -15,   -26,   -26,   -26,   -16,   -23,   -26,   -26,   -26,   -26,
   -10,   -20,   -20,   -20,   -15,   -15,   -15,   -15,   -17,   -18,
   -19,   -11,   -12,   -13,   -14 ]

racc_goto_table = [
    10,    34,    12,    13,    17,     7,     8,    40,    19,    20,
    27,    28,   nil,    22,    15,    25,    29,    48,    49,    50,
    30,    51,    52,    53,    54,   nil,   nil,   nil,    41,    42,
    43,    24,   nil,    44,    45,    46,    47,   nil,   nil,   nil,
    35 ]

racc_goto_check = [
     6,    11,     6,     6,     7,     1,     3,     9,    10,    10,
    12,    12,   nil,     6,     1,     6,     7,    11,    11,    11,
     6,     9,     9,     9,     9,   nil,   nil,   nil,     6,     6,
     6,     8,   nil,     6,     6,     6,     6,   nil,   nil,   nil,
     8 ]

racc_goto_pointer = [
   nil,     5,   nil,     5,   nil,   nil,    -3,    -6,    14,   -23,
    -4,   -24,    -9 ]

racc_goto_default = [
   nil,   nil,     1,   nil,     2,     4,   nil,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :NL => 2,
 :OPTGROUP => 3,
 :NAME => 4,
 :COLON => 5,
 :ITEM => 6,
 :DEFAULT_ITEM => 7,
 :SPACE => 8 }

racc_use_result_var = true

racc_nt_base = 9

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'NL',
'OPTGROUP',
'NAME',
'COLON',
'ITEM',
'DEFAULT_ITEM',
'SPACE',
'$start',
'options',
'option_entry',
'more_options',
'item',
'group',
'ws',
'more_optgroup',
'freeform_name',
'freeform_name_suffix',
'noncolon_name',
'noncolon_name_suffix',
'item_value']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/options_parser.y', 27
  def _reduce_1( val, _values, result )
 return [val[0], *val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 28
  def _reduce_2( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 31
  def _reduce_3( val, _values, result )
 return val[1]
   result
  end
.,.,

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

module_eval <<'.,.,', 'lib/options_parser.y', 39
  def _reduce_7( val, _values, result )
 return {:group_depth => val[2], :name => val[3]}
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 43
  def _reduce_8( val, _values, result )
 return val[3] + 1
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 44
  def _reduce_9( val, _values, result )
 return 1
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 48
  def _reduce_10( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 51
  def _reduce_11( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 52
  def _reduce_12( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 53
  def _reduce_13( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 54
  def _reduce_14( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 55
  def _reduce_15( val, _values, result )
 return ""
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 59
  def _reduce_16( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 62
  def _reduce_17( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 63
  def _reduce_18( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 64
  def _reduce_19( val, _values, result )
 return val.join()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 65
  def _reduce_20( val, _values, result )
 return ""
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 71
  def _reduce_21( val, _values, result )
    return {:name => val[2], :default => false, :value => val[3], :item_depth => val[0].length }
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 74
  def _reduce_22( val, _values, result )
    return {:name => val[2], :default => true, :value => val[3], :item_depth => val[0].length }
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 76
  def _reduce_23( val, _values, result )
 return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 77
  def _reduce_24( val, _values, result )
 @item_id += 1; return @item_id.to_s
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 80
  def _reduce_25( val, _values, result )
 return val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/options_parser.y', 81
  def _reduce_26( val, _values, result )
 return ""
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class OptionsParser
